### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by fakerybakery** [Y-ichen/FlexiFilm#1]
Hi,
Thanks for releasing the paper & details! Is there any timeline for releasing the code?
Thank you!

**Comment by Y-ichen** [comment]
Hi there,

Thank you for your interest in our paper! We really appreciate it.

We are currently working on cleaning up and documenting the codebase to make it more user-friendly and accessible. We are aiming to release the code within the next two months, including training codes and inference codes.

Thank you for your patience and understanding. We're excited to share our code with the community soon!

Best regards,
Yichen
